### ISSUE TITLE
Scientific Notation in SVG results in undefined or NaN

### ISSUE THREAD

**Issue by kckern** [stadline/svg-flatten#6]
SVG files support scientific notation in the transform attribute.  eg:

`<circle class="fil5" transform="matrix(1.66664 1.46772 -9.37604E-001 2.60895 1841.36 1511.12)" r="45.71"/>`

When this is run through svg-flatten, it does not get parsed correctly.  Note the `NaN` and `undefined` in the radius:

`<path class="fil5" transform="matrix(1.66664 1.46772 -9.37604E-001 2.60895 1841.36 1511.12)" d="MNaN,undefineda45.71,45.71 0 1,0 91.42,0a45.71,45.71 0 1,0 -91.42,0"/>`

**Comment by alex-pex** [comment]
Interesting, I didn't know it was supported.
Can you suggest a change (pull-request)? Or do you want me to investigate?

**Comment by alex-pex** [comment]
I wrote a test case, and the problem is your circle shape doesn't specify the position of its center point using `cx` and `cy` (only the radius of the circle using `r`)

Where is it positioned in that case ? I can default to 0 but it's weird

EDIT: The default value is indeed zero
![image](https://user-images.githubusercontent.com/368155/199931806-007113ad-8408-4ad9-95b2-bcc9740bdd80.png)

**Comment by kckern** [comment]
Here's the full svg doc that had trouble:
https://pastebin.com/raw/uKWAc7Gh

Seemed related to `clipPath`

**Comment by alex-pex** [comment]
The problem with scientific notation was in reality default circle attribute values not used in pathify transformation.

clipPath doesn't work properly because some style attributes are lost. I won't support clipPath squashing, unless someone make a PR. Maybe I can protect them from being transformed and they can remain *as-is* in the final result, but I don't know if it fits your use case.

Can you elaborate what you're trying to achieve using this lib?

**Comment by alex-pex** [comment]
I added some details in the README
